services:
    app.api_exception.subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        arguments:
            - "%kernel.debug%"
        tags:
            - { name: kernel.event_subscriber }

    event.listener.device_postback:
        class: AppBundle\EventListener\DevicePostbackListener
        arguments:
            - "@service_container"
        tags:
            - {name: doctrine.event_listener, event: postUpdate}